spring:
  application:
    name: to-do-list
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3308/to_do_list
    username: root
    password: ${ENV_MYSQL_PASSWORD}
  sql:
    init:
      schema-locations: classpath:db/sql/init.sql
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tagsSorter: "alpha"
jwt:
  secret:
    key: ${ENV_JWT_KEY}